services:
  elasticsearch:
    image: elasticsearch:7.8.1
    ports:
      - 9200:9200
    environment:
      discovery.type: 'single-node'
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: 'changeme'
    networks:
      - laravel
  kibana:
    image: kibana:7.8.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - laravel
  db:
    image: mysql
    restart: always
    volumes:
      - mysql-ecd:/var/lib/mysql
    networks:
      - laravel
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 9999:80
    environment:
      - PMA_ARBITRARY=1
    networks:
      - laravel
    depends_on:
      - db
  ecd:
    image: ${ECD_IMAGE}:nginx_${ECD_TAG}
    build:
        args:
            PHP_PROXY: $PHP_HOST:$PHP_PORT
            UID: 1000
            GID: 1000
        context: .
        dockerfile: dockerfiles/nginx/Dockerfile
    env_file: ./.env
    restart: unless-stopped
    ports:
        - $PORT:80
    volumes:
      - C:/xampp/htdocs/develop/ECD:/var/www/html/storage
    networks:
      - laravel
  php:
      image: ${ECD_IMAGE}:${ECD_TAG}
      build:
          args:
              PHP_PORT: $PHP_PORT
              UID: 1000
              GID: 1000
          context: .
          dockerfile: dockerfiles/php/Dockerfile
          target: ${ENVIRONMENT}
      env_file: ./.env
      restart: unless-stopped
      ports:
          - $PHP_PORT:$PHP_PORT
      volumes:
          - ./:/var/www/html:delegated
          - vendor:/var/www/html/vendor
      networks:
          - laravel
  redis:
    image: redis:alpine
    container_name: laravel_redis
    networks:
      - laravel
    ports:
      - "6379:6379"
volumes:
  vendor:
    driver: local
  mysql-ecd:
    driver: local

networks:
  laravel:
    driver: bridge
